In [1]:
import pandas as pd

CB = pd.read_csv('kyochon.csv', encoding='CP949', index_col=0, header=0, engine='python')

CB.head()

   store sido gungu                 store_address
0   가락2호   서울   송파구               서울 송파구 가락동 75-7
1  가산디지털   서울   금천구  서울 금천구 가산동 371-6 가산비지니스센터 2층
2     가양   서울   강서구               서울 강서구 등촌동 75-1
3    강남역   서울   서초구             서울 서초구 서초동 1309-6
4   강서구청   서울   강서구             서울 강서구 화곡동 986-16

In [3]:
addr = []
for address in CB.store_address:
  addr.append(str(address).split())
addr

[['서울', '송파구', '가락동', '75-7'],
 ['서울', '금천구', '가산동', '371-6', '가산비지니스센터', '2층'],
 ['서울', '강서구', '등촌동', '75-1'],
 ['서울', '서초구', '서초동', '1309-6'],
 ['서울', '강서구', '화곡동', '986-16'],
 ['서울', '강동구', '강일동', '679-3', '리슈빌오피스텔'],
 ['서울', '구로구', '개봉동', '403-159'],
 ['서울', '강남구', '개포동', '1229-18'],
 ['서울', '송파구', '가락동', '180-9'],
 ['서울', '광진구', '화양동', '9-18'],
 ['서울', '동대문구', '회기동', '42-16'],
 ['서울', '강동구', '고덕동', '650-1'],
 ['서울', '구로구', '개봉1동', '126-4'],
 ['서울', '노원구', '공릉동', '338-6'],
 ['서울', '노원구', '공릉동', '461-1'],
 ['서울', '광진구', '광장동', '530-13'],
 ['서울', '구로구', '구로동', '74-30'],
 ['서울', '구로구', '구로동', '826-1'],
 ['서울', '은평구', '갈현동', '464-14'],
 ['서울', '광진구', '구의동', '257-70'],
 ['서울', '강남구', '개포동', '1229-18'],
 ['서울', '강남구', '논현동', '164-16'],
 ['서울', '강남구', '대치동936'],
 ['서울', '강남구', '대치동', '989-4'],
 ['서울', '강남구', '도곡동', '416-4'],
 ['서울', '강남구', '삼성동', '44-18'],
 ['서울', '강남구', '자곡동', '611'],
 ['서울', '강남구', '신사동', '640-5', '대성빌딩', '1층', '1호'],
 ['서울', '강남구', '역삼동', '837-15'],
 ['서울', '강남구', '일원동', '645'],
 ['서울', '강남구', '수서동', '747', '삼성아파트', '상가', '104호'],
 ['서울', '강남구', '청담동', '65', '진흥아파트상가'],
 ['서울', '강동구', '강일동', '679-3', '리슈빌오피스텔'],
 ['서울', '강동구', '고덕동', '650-1'],
 ['서울', '강동구', '길동', '347-31'],
 ['서울', '강동구', '길동', '388-3'],
 ['서울', '강동구', '둔촌동', '454-5'],
 ['서울', '강동구', '명일동', '328-2'],
 ['서울', '강동구', '고덕동', '200-3'],
 ['서울', '강동구', '성내2동', '509-7', '1층'],
 ['서울', '강동구', '암사동', '504-37'],
 ['서울', '강동구', '암사동', '446-18'],
 ['서울', '강동구', '천호동', '550번지', '강천빌딩'],
 ['서울', '강북구', '우이동', '72-148'],
 ['서울', '강북구', '미아5동', '1264-233'],
 ['서울', '강북구', '미아동', '55-5'],
 ['서울', '강북구', '미아동', '131-8'],
 ['서울', '강북구', '번동', '169-1'],
 ['서울', '강북구', '수유동', '385-2'],
 ['서울', '강북구', '번동', '461-127'],
 ['서울', '강서구', '등촌동', '75-1'],
 ['서울', '강서구', '화곡동', '986-16'],
 ['서울', '강서구', '화곡동', '343-62', '라인씨티', '1층'],
 ['서울', '강서구', '등촌동', '649-14'],
 ['서울', '강서구', '강서로', '마곡동', '784-11', '마곡오드카운티1차', '111호'],
 ['서울', '강서구', '마곡동', '774-1'],
 ['서울', '강서구', '내발산동', '655-6번지', '1층', '13호'],
 ['서울', '강서구', '방화동', '571-1'],
 ['서울', '강서구', '방화2동', '580-27'],
 ['서울', '강서구', '염창동', '249-5'],
 ['서울', '강서구', '화곡동', '400-45'],
 ['서울', '관악구', '봉천동', '861-7'],
 ['서울', '관악구', '봉천동', '1674-20'],
 ['서울', '관악구', '봉천동', '1632-9'],
 ['서울', '관악구', '봉천동', '931-12'],
 ['서울', '관악구', '봉천3동', '7-291'],
 ['서울', '관악구', '신림동', '518-56'],
 ['서울', '관악구', '신림동', '1680-15'],
 ['서울', '관악구', '신림동', '241-66'],
 ['서울', '광진구', '화양동', '9-18'],
 ['서울', '광진구', '광장동', '530-13'],
 ['서울', '광진구', '구의동', '257-70'],
 ['서울', '광진구', '자양3동', '584-28'],
 ['서울', '광진구', '자양동', '624-42'],
 ['서울', '광진구', '중곡동', '243-1'],
 ['서울', '광진구', '중곡동', '24-2'],
 ['서울', '구로구', '개봉동', '403-159'],
 ['서울', '구로구', '개봉1동', '126-4'],
 ['서울', '구로구', '구로동', '74-30'],
 ['서울', '구로구', '구로동', '826-1'],
 ['서울', '구로구', '구로동', '704-38'],
 ['서울', '구로구', '고척동', '343'],
 ['서울', '구로구', '신도림동', '648', '신도림6차대림아파트', '상가', '902동', '111호'],
 ['서울', '구로구', '오류1동', '10-3'],
 ['서울', '구로구', '오류동', '203-1', '1층'],
 ['서울', '금천구', '가산동', '371-6', '가산비지니스센터', '2층'],
 ['서울', '금천구', '독산동', '888-20', '102호,103호'],
 ['서울', '금천구', '독산동', '1059-4'],
 ['서울', '금천구', '시흥2동', '264-17'],
 ['서울', '금천구', '시흥1동', '905-5'],
 ['서울', '노원구', '공릉동', '338-6'],
 ['서울', '노원구', '공릉동', '461-1'],
 ['서울', '노원구', '상계동', '749-5'],
 ['서울', '노원구', '상계동', '456-70'],
 ['서울', '노원구', '중계동', '137-39', '정진빌라', '1층'],
 ['서울', '노원구', '월계1동', '73-13'],
 ['서울', '노원구', '상계동', '1118'],
 ['서울', '노원구', '중계1동', '360-9'],
 ['서울', '노원구', '중계동', '503'],
 ['서울', '노원구', '하계1동', '251', '청구상가', '201동', '101호'],
 ['서울', '도봉구', '도봉2동', '623-163'],
 ['서울', '도봉구', '방학동', '659-32'],
 ['서울', '도봉구', '방학동', '263-56'],
 ['서울', '도봉구', '쌍문3동', '88-127'],
 ['서울', '도봉구', '창동', '568-2'],
 ['서울', '도봉구', '창동', '296-37'],
 ['서울', '동대문구', '회기동', '42-16'],
 ['서울', '동대문구', '답십리동', '53-50'],
 ['서울', '동대문구', '전농1동', '141-141'],
 ['서울', '동대문구', '이문동', '255-222'],
 ['서울', '동대문구', '제기동', '142-8'],
 ['서울', '동대문구', '왕산로28길', '55'],
 ['서울', '동대문구', '전농동', '1-171'],
 ['서울', '동대문구', '장안동', '375-3'],
 ['서울', '동대문구', '청량리동', '50-3'],
 ['서울', '동작구', '노량진동', '37-1'],
 ['서울', '동작구', '사당3동', '155-2', '1F'],
 ['서울', '동작구', '사당동', '220-119'],
 ['서울', '동작구', '상도동', '535', '상도2차', '두산위브트레지움아파트', '상가'],
 ['서울', '동작구', '상도1동', '587'],
 ['서울', '동작구', '신대방동', '607-28'],
 ['서울', '동작구', '대방동', '407-46'],
 ['서울', '동작구', '흑석동', '180-6'],
 ['서울', '마포구', '도화동', '179-8', '1,2층'],
 ['서울', '마포구', '망원동', '482-9'],
 ['서울', '마포구', '상암동', '34-45'],
 ['서울', '마포구', '성산동', '592'],
 ['서울', '마포구', '신공덕동', '159(신공덕', '래미안상가', '1동109호)'],
 ['서울', '마포구', '신수동', '451번지', '세양청마루아파트', '상가', '101호'],
 ['서울', '마포구', '아현동', '774', '마포래미안', '푸르지오', '101동', '상가', '114호'],
 ['서울', '마포구', '연남동', '369-20'],
 ['서울', '마포구', '서교동', '371-3'],
 ['서울', '서대문구', '냉천동', '226'],
 ['서울', '서대문구', '남가좌동', '344-7'],
 ['서울', '서대문구', '북가좌동', '385-8'],
 ['서울', '서대문구', '북아현동', '1006'],
 ['서울', '서대문구', '창천동', '41-14'],
 ['서울', '서대문구', '연희3동', '344-26'],
 ['서울', '서대문구', '홍제동', '279-52'],
 ['서울', '서대문구', '홍제동', '326-20'],
 ['서울', '서초구', '서초동', '1309-6'],
 ['서울', '서초구', '반포동', '1053', 'H동', '26호'],
 ['서울', '서초구', '반포동', '53-7'],
 ['서울', '서초구', '방배동', '761-8'],
 ['서울', '서초구', '방배동', '912-8'],
 ['서울', '서초구', '서초동', '1357-56'],
 ['서울', '서초구', '서초동', '1669-15'],
 ['서울', '서초구', '서초동', '1579-5'],
 ['서울', '서초구', '양재동', '327-2'],
 ['서울', '서초구', '우면동', '720'],
 ['서울', '서초구', '잠원동', '15-4'],
 ['서울', '성동구', '금호동4가', '1380'],
 ['서울', '성동구', '성수동2가', '235-1'],
 ['서울', '성동구', '성수동2가', '289-251'],
 ['서울', '성동구', '하왕십리동', '946-15'],
 ['서울', '성동구', '홍익동', '131-1'],
 ['서울', '성동구', '응봉동', '100'],
 ['서울', '성동구', '행당동', '3-29'],
 ['서울', '성북구', '하월곡동', '17-1'],
 ['서울', '성북구', '동소문동', '6가', '227', '1층'],
 ['서울', '성북구', '보문동2가', '40'],
 ['서울', '성북구', '화랑로', '265'],
 ['서울', '성북구', '정릉4동', '285-4'],
 ['서울', '성북구', '정릉동', '175-24'],
 ['서울', '성북구', '종암동', '3-544'],
 ['서울', '송파구', '가락동', '75-7'],
 ['서울', '송파구', '가락동', '180-9'],
 ['서울', '송파구', '거여동', '32-6'],
 ['서울', '송파구', '문정동', '620', '송파푸르지오시티', 'B09호'],
 ['서울', '송파구', '방이동', '59-1'],
 ['서울', '송파구', '오금동', '41-23', '성암빌딩', '1층'],
 ['서울', '송파구', '석촌동', '163-1'],
 ['서울', '송파구', '송파동', '147'],
 ['서울', '송파구', '풍납동', '401-4'],
 ['서울', '송파구', '장지동', '894', '위례아이파크', '상가1동', '103호,', '104호'],
 ['서울', '송파구', '잠실본동', '313-8'],
 ['서울', '송파구', '신천동', '11-4'],
 ['서울', '송파구', '문정동', '102-1'],
 ['서울', '송파구', '가락동', '479', '헬리오시티상가', 'A동', '3,4호'],
 ['서울', '양천구', '목동', '722-8', '호성빌딩'],
 ['서울', '양천구', '목동', '797-3'],
 ['서울', '양천구', '목동', '909-8', '이화프라자', '1층', '101호'],
 ['서울', '양천구', '목동', '940', '현대아이파크상가', '102'],
 ['서울', '양천구', '신월동', '602-8'],
 ['서울', '양천구', '신월7동', '972-6'],
 ['서울', '양천구', '신정동', '1022-5'],
 ['서울', '양천구', '신정동', '1267', '목동뉴프라자'],
 ['서울', '양천구', '신정동', '1296', '아이파크', '상가', '1층'],
 ['서울', '양천구', '신월동', '23-17'],
 ['서울', '영등포구', '영등포동8가', '35-1'],
 ['서울', '영등포구', '대림3동', '783-6'],
 ['서울', '영등포구', '문래동3가', '77-34'],
 ['서울', '영등포구', '양평동4가', '147-3'],
 ['서울', '영등포구', '신길동', '296-14'],
 ['서울', '영등포구', '신길7동', '674'],
 ['서울', '영등포구', '신길동', '445-2'],
 ['서울', '영등포구', '여의도동', '44-31'],
 ['서울', '영등포구', '신길동', '232-42'],
 ['서울', '영등포구', '영등포동3가', '21-10'],
 ['서울', '용산구', '이촌1동', '301-153', '오성상가', '103'],
 ['서울', '용산구', '보광동', '217-13'],
 ['서울', '용산구', '청파동2가', '90-11'],
 ['서울', '용산구', '한강로2가', '122-5'],
 ['서울', '용산구', '용문동', '28-26'],
 ['서울', '용산구', '한남동', '828'],
 ['서울', '용산구', '후암동', '244-59'],
 ['서울', '은평구', '갈현동', '464-14'],
 ['서울', '은평구', '녹번동', '82-47'],
 ['서울특별시', '은평구', '대조동', '231'],
 ['서울', '은평구', '불광동', '554-1', '라비앙프라자1층', '101호'],
 ['서울', '은평구', '신사동', '29-13'],
 ['서울', '은평구', '역촌동', '55-1'],
 ['서울', '은평구', '불광동', '484-72'],
 ['서울', '은평구', '진관동', '22', '은평뉴타운상가', '914-103호'],
 ['서울', '은평구', '응암동', '236-33'],
 ['서울', '은평구', '응암동', '595-51'],
 ['서울', '은평구', '증산동', '209-18'],
 ['서울', '종로구', '명륜동4가', '113-1'],
 ['서울', '종로구', '숭인2동', '183-13'],
 ['서울', '종로구', '화동', '138-7'],
 ['서울', '종로구', '관철동', '13-13'],
 ['서울', '종로구', '평창동', '158-1'],
 ['서울', '중구', '창신동', '464-6'],
 ['서울', '중구', '태평로2가', '55'],
 ['서울', '중구', '신당동', '846'],
 ['서울', '중구', '신당동', '374-14'],
 ['서울', '중랑구', '망우동', '149-7'],
 ['서울', '중랑구', '면목본동', '72-43'],
 ['서울', '중랑구', '면목2동', '191-126'],
 ['서울', '중랑구', '묵동', '175-2'],
 ['서울', '중랑구', '면목동', '496-14'],
 ['서울', '중랑구', '상봉동', '91-1'],
 ['서울', '중랑구', '신내동', '797'],
 ['서울', '중랑구', '중화동', '304-34'],
 ['부산', '부산진구', '가야동', '478'],
 ['부산', '남구', '감만1동', '158-6'],
 ['부산', '부산진구', '개금동', '2-1'],
 ['부산', '부산진구', '개금1동', '201-6'],
 ['부산', '연제구', '거제동', '891-14'],
 ['부산', '수영구', '광안동', '168-3'],
 ['부산', '사상구', '괘법동', '516-1'],
 ['부산', '사하구', '괴정동', '487-24'],
 ['부산', '금정구', '구서2동', '1024-1'],
 ['부산', '북구', '구포3동', '1228-1'],
 ['부산', '강서구', '명지동', '3412-6'],
 ['부산', '북구', '금곡동', '57-6'],
 ['부산', '기장군', '기장읍', '동부리', '134-2'],
 ['부산', '서구', '충무동2가', '3-1'],
 ['부산', '금정구', '남산동', '99-6'],
 ['부산', '중구', '중앙동1가', '23-6'],
 ['부산', '사하구', '다대2동', '85-5'],
 ['부산', '사하구', '다대동', '1014'],
 ['부산', '부산진구', '당감동', '367-2'],
 ['부산', '사하구', '괴정동', '577-42'],
 ['부산', '강서구', '명지동', '3412-6'],
 ['부산', '강서구', '명지동', '3432-1', '2동', '102호'],
 ['부산', '강서구', '명지동', '3256-5'],
 ['부산', '강서구', '신호동', '317-15'],
 ['부산', '강서구', '지사동', '1191-5'],
 ['부산', '금정구', '구서2동', '1024-1'],
 ['부산', '금정구', '남산동', '99-6'],
 ['부산', '금정구', '부곡동', '23-15'],
 ['부산', '금정구', '부곡1동', '324-20'],
 ['부산', '금정구', '금강로', '장전동', '418-13'],
 ['부산', '금정구', '서동', '210-6'],
 ['부산', '금정구', '장전동', '134-19'],
 ['부산', '기장군', '기장읍', '동부리', '134-2'],
 ['부산', '기장군', '일광면', '삼성리', '833-4'],
 ['부산', '기장군', '정관면', '매학리', '751-8'],
 ['부산', '기장군', '모전리', '747-7'],
 ['부산', '남구', '감만1동', '158-6'],
 ['부산', '남구', '대연동', '1013-8'],
 ['부산', '남구', '대연동', '52-7'],
 ['부산', '남구', '대연동', '1161-9'],
 ['부산', '남구', '용호동', '176-30'],
 ['부산', '남구', '대연동', '1543-33'],
 ['부산', '남구', '문현동', '359-5'],
 ['부산', '남구', '문현1동', '127-56'],
 ['부산', '남구', '용호동', '555-19'],
 ['부산', '동구', '범일동', '833-2'],
 ['부산', '동구', '수정동', '295-3'],
 ['부산', '동구', '초량동', '132-1'],
 ['부산', '동래구', '명륜1동', '673-9'],
 ['부산', '동래구', '명장동', '26-24번지', '국제아파트', '상가', '106호'],
 ['부산', '동래구', '복천동', '476-1'],
 ['부산', '동래구', '사직동', '137-5번지'],
 ['부산', '동래구', '사직동', '89-16'],
 ['부산', '동래구', '수안동', '192-4'],
 ['부산', '동래구', '안락동', '670-13'],
 ['부산', '동래구', '온천동', '210-5번지'],
 ['부산', '동래구', '온천동', '1411-47'],
 ['부산', '동래구', '안락동', '471-41'],
 ['부산', '부산진구', '가야동', '478'],
 ['부산', '부산진구', '개금동', '2-1'],
 ['부산', '부산진구', '개금1동', '201-6'],
 ['부산', '부산진구', '당감동', '367-2'],
 ['부산', '부산진구', '범천동', '1278-11'],
 ['부산', '부산진구', '부암동', '301-33'],
 ['부산', '부산진구', '부전동', '266-24'],
 ['부산', '부산진구', '양정동', '310-6'],
 ['부산', '부산진구', '연지동', '40-12'],
 ['부산', '부산진구', '초읍동', '288-6'],
 ['부산', '북구', '구포3동', '1228-1'],
 ['부산', '북구', '금곡동', '57-6'],
 ['부산', '북구', '덕천3동', '781-2'],
 ['부산', '북구', '덕천동', '402-12'],
 ['부산', '북구', '만덕동', '294'],
 ['부산', '북구', '만덕3동', '915-6'],
 ['부산', '북구', '화명동', '749'],
 ['부산', '북구', '화명동', '182-5(2층)'],
 ['부산', '북구', '화명동', '2266-1'],
 ['부산', '사상구', '괘법동', '516-1'],
 ['부산', '사상구', '덕포동', '767-10'],
 ['부산', '사상구', '주례동', '55-176'],
 ['부산', '사상구', '모라동', '1349-'],
 ['부산', '사상구', '주례2동', '3-17'],
 ['부산', '사상구', '엄궁동', '40-94'],
 ['부산', '사상구', '학장동', '산149-16'],
 ['부산', '사하구', '괴정동', '487-24'],
 ['부산', '사하구', '다대2동', '85-5'],
 ['부산', '사하구', '다대동', '1014'],
 ['부산', '사하구', '괴정동', '577-42'],
 ['부산', '사하구', '신평동', '262-20'],
 ['부산', '사하구', '장림동', '590'],
 ['부산', '사하구', '하단2동', '506-15'],
 ['부산', '사하구', '하단동', '605-42'],
 ['부산', '강서구', '명지동', '3412-6'],
 ['부산', '서구', '충무동2가', '3-1'],
 ['부산', '서구', '서대신동1가', '163-1'],
 ['부산', '강서구', '명지동', '3432-1', '2동', '102호'],
 ['부산', '강서구', '명지동', '3256-5'],
 ['부산', '서구', '암남동', '64-2', '상가동', '108호,109호(암남동)'],
 ['부산', '강서구', '신호동', '317-15'],
 ['부산', '서구', '부민동1가', '11-3'],
 ['부산', '강서구', '지사동', '1191-5'],
 ['부산', '수영구', '광안동', '168-3'],
 ['부산', '수영구', '망미동', '413-11'],
 ['부산', '수영구', '민락동', '165-15'],
 ['부산', '수영구', '수영동', '503-23'],
 ['부산', '연제구', '거제동', '891-14'],
 ['부산', '연제구', '거제3동', '34-19'],
 ['부산', '연제구', '연산동', '479-9'],
 ['부산', '연제구', '연산4동', '578-1', '삼익아파트', '상가', '101호'],
 ['부산', '연제구', '연산동', '2133-48'],
 ['부산', '영도구', '남항동1가', '82'],
 ['부산', '영도구', '동삼동', '219-146'],
 ['부산', '영도구', '영선동1가', '69-2,', '69-3'],
 ['부산', '영도구', '청학동', '13-14'],
 ['부산', '중구', '중앙동1가', '23-6'],
 ['부산', '중구', '대청동4가', '82-13'],
 ['부산', '해운대구', '우동', '1434-2'],
 ['부산', '해운대구', '반송2동', '216-150'],
 ['부산', '해운대구', '반여동', '1628-5'],
 ['부산', '해운대구', '송정동', '227-7'],
 ['부산', '해운대구', '우동', '1090-13'],
 ['부산', '해운대구', '반여동', '1291-1019'],
 ['부산', '해운대구', '재송동', '1083-10'],
 ['부산', '해운대구', '좌동', '970'],
 ['부산', '해운대구', '좌동', '1341-8'],
 ['부산', '해운대구', '좌동', '1484-1'],
 ['부산', '해운대구', '우동', '639-4'],
 ['대구', '달서구', '감삼동', '317-3'],
 ['대구시', '남구', '양지로', '107'],
 ['대구', '북구', '관음동', '1383-9'],
 ['대구', '북구', '태전동', '1074-6'],
 ['대구', '달성군', '구지면', '응암리', '1204-2'],
 ['대구', '북구', '사수동', '912'],
 ['대구', '중구', '남산3동', '2466-14'],
 ['대구', '서구', '내당동', '219-7'],
 ['대구', '달성군', '논공읍', '북리', '803-128'],
 ['대구', '달성군', '다사읍', '죽곡리', '809-1'],
 ['대구', '서구', '비산동', '440-5'],
 ['대구', '달서구', '도원동', '1442-2', '1층', '107호'],
 ['대구', '동구', '각산동', '1098-5', '102호'],
 ['대구', '남구', '대명동', '1098-4'],
 ['대구', '동구', '신암동', '345-3'],
 ['대구', '북구', '동변동', '669-4'],
 ['대구', '북구', '동천동', '906-3'],
 ['대구', '동구', '검사동', '1111'],
 ['대구', '동구', '동호동', '384-7'],
 ['대구', '달서구', '두류동', '620-12'],
 ['대구시', '남구', '양지로', '107'],
 ['대구', '남구', '대명동', '1098-4'],
 ['대구', '남구', '봉덕동', '687-32'],
 ['대구', '남구', '대명동', '780-3'],
 ['대구', '남구', '이천동', '184-9'],
 ['대구', '달서구', '감삼동', '317-3'],
 ['대구', '달서구', '도원동', '1442-2', '1층', '107호'],
 ['대구', '달서구', '두류동', '620-12'],
 ['대구', '달서구', '상인동', '1555-1'],
 ['대구', '달서구', '신당동', '1761-5'],
 ['대구', '달서구', '송현1동', '207-2'],
 ['대구', '달서구', '월성동', '1264번지', '트럼프스타', 'B/D', '106호'],
 ['대구', '달서구', '용산1동', '954-6'],
 ['대구', '달서구', '용산동', '499-2'],
 ['대구', '달서구', '본동', '1135-4'],
 ['대구', '달서구', '장기동', '826-6'],
 ['대구', '달서구', '진천동', '504'],
 ['대구', '달서구', '호산동', '357-116'],
 ['대구', '달성군', '구지면', '응암리', '1204-2'],
 ['대구', '달성군', '논공읍', '북리', '803-128'],
 ['대구', '달성군', '다사읍', '죽곡리', '809-1'],
 ['대구', '달성군', '화원읍', '명곡리', '320-1'],
 ['대구', '달성군', '다사읍', '서재리', '423-15'],
 ['대구', '달성군', '옥포읍', '교항리', '2911'],
 ['대구', '달성군', '유가면', '봉리', '606', '하이젠스타', '115호'],
 ['대구', '달성군', '화원읍', '천내리', '241-1'],
 ['대구', '동구', '각산동', '1098-5', '102호'],
 ['대구', '동구', '신암동', '345-3'],
 ['대구', '동구', '검사동', '1111'],
 ['대구', '동구', '동호동', '384-7'],
 ['대구', '동구', '방촌동', '1118-121'],
 ['대구', '동구', '신천동', '501-5'],
 ['대구', '동구', '신청동', '377-12'],
 ['대구', '동구', '율하동', '1311번지', '102호'],
 ['대구', '동구', '지묘동', '808-3'],
 ['대구', '동구', '지저동', '833-15'],
 ['대구', '북구', '관음동', '1383-9'],
 ['대구', '북구', '태전동', '1074-6'],
 ['대구', '북구', '사수동', '912'],
 ['대구', '북구', '동변동', '669-4'],
 ['대구', '북구', '동천동', '906-3'],
 ['대구', '북구', '복현동', '426-5'],
 ['대구', '북구', '복현동', '539', '-110', '복현서한타운', '상가', '103호'],
 ['대구', '북구', '산격동', '1400-20'],
 ['대구', '북구', '대현동', '153-4'],
 ['대구', '북구', '연경동', '949-1'],
 ['대구', '북구', '노원동3가', '892-1'],
 ['대구', '북구', '읍내동', '1449', '202동', '103호'],
 ['대구', '북구', '칠성동2가', '42-9'],
 ['대구', '북구', '침산동', '457-31'],
 ['대구', '북구', '태전동', '254-30'],
 ['대구', '북구', '매천동', '682'],
 ['대구', '북구', '학정동', '282-14'],
 ['대구', '달서구', '감삼동', '317-3'],
 ['대구', '서구', '내당동', '219-7'],
 ['대구', '서구', '비산동', '440-5'],
 ['대구', '달서구', '도원동', '1442-2', '1층', '107호'],
 ['대구', '달서구', '두류동', '620-12'],
 ['대구', '달서구', '상인동', '1555-1'],
 ['대구', '달서구', '신당동', '1761-5'],
 ['대구', '달서구', '송현1동', '207-2'],
 ['대구', '달서구', '월성동', '1264번지', '트럼프스타', 'B/D', '106호'],
 ['대구', '달서구', '용산1동', '954-6'],
 ['대구', '달서구', '용산동', '499-2'],
 ['대구', '달서구', '본동', '1135-4'],
 ['대구', '달서구', '장기동', '826-6'],
 ['대구', '달서구', '진천동', '504'],
 ['대구', '서구', '평리동', '1217-2'],
 ['대구', '달서구', '호산동', '357-116'],
 ['대구', '수성구', '만촌동', '849-2'],
 ['대구', '수성구', '만촌1동', '1330-12'],
 ['대구', '수성구', '범물동', '1374-4'],
 ['대구', '수성구', '범어동', '203-18'],
 ['대구', '수성구', '범어동', '478-12'],
 ['대구', '수성구', '수성동4가', '1022-11'],
 ['대구', '수성구', '두산동', '653-5'],
 ['대구', '수성구', '매호동', '1328-12'],
 ['대구', '수성구', '시지동', '489-2'],
 ['대구', '수성구', '신매동', '593-4'],
 ['대구', '수성구', '중동', '97-5'],
 ['대구', '수성구', '상동', '380-2'],
 ['대구', '수성구', '두산동', '133-1'],
 ['대구', '중구', '남산3동', '2466-14'],
 ['대구', '중구', '남일동', '33-9'],
 ['인천', '서구', '가정동', '614-14'],
 ['인천', '서구', '가좌동', '30-78'],
 ['인천', '남동구', '구월동', '70-80'],
 ['인천', '부평구', '갈산동', '55-8'],
 ['인천', '강화군', '강화읍', '갑곳리', '199-1'],
 ['인천', '서구', '검단로', '왕길동', '637-1'],
 ['인천', '서구', '검암동', '626-2번지', '태건프라자', '105호'],
 ['인천', '계양구', '계산동', '1081-10'],
 ['인천', '계양구', '계산동', '61-2'],
 ['인천', '계양구', '계산동', '942-30'],
 ['인천', '중구', '운서동', '2801-3'],
 ['인천', '남구', '관교동', '321-5'],
 ['인천', '남동구', '구월동', '1133-13'],
 ['인천', '남동구', '구월동', '1517-2'],
 ['인천', '남동구', '논현동', '620-8'],
 ['인천', '남동구', '논현동', '752-1'],
 ['인천', '서구', '마전동', '585'],
 ['인천', '미추홀구', '도화동', '1005-3', '스카이프라자2'],
 ['인천', '연수구', '동춘동', '934-1'],
 ['인천', '남동구', '만수동', '1045', '103호'],
 ['인천', '강화군', '강화읍', '갑곳리', '199-1'],
 ['인천', '계양구', '계산동', '1081-10'],
 ['인천', '계양구', '계산동', '61-2'],
 ['인천', '계양구', '계산동', '942-30'],
 ['인천', '계양구', '박촌동', '52-3'],
 ['인천', '계양구', '작전동', '149-1'],
 ['인천', '계양구', '효성1동', '21-11', '현대아파트', '상가동', '101호,', '102호,', '103호'],
 ['인천', '계양구', '효성2동', '273-3'],
 ['인천', '남구', '관교동', '321-5'],
 ['인천', '남구', '용현동', '558-32'],
 ['인천', '남구', '용현동', '630-45'],
 ['인천', '남구', '주안동', '1523-2'],
 ['인천', '남구', '학익동', '293-37'],
 ['인천', '남동구', '구월동', '70-80'],
 ['인천', '남동구', '구월동', '1133-13'],
 ['인천', '남동구', '구월동', '1517-2'],
 ['인천', '남동구', '논현동', '620-8'],
 ['인천', '남동구', '논현동', '752-1'],
 ['인천', '남동구', '만수동', '1045', '103호'],
 ['인천', '남동구', '만수동', '1118-2'],
 ['인천', '남동구', '간석3동', '921-14'],
 ['인천', '남동구', '서창동', '706'],
 ['인천', '남동구', '논현동', '671-3'],
 ['인천', '남동구', '구월동', '70-80'],
 ['인천', '남동구', '구월동', '1133-13'],
 ['인천', '남동구', '구월동', '1517-2'],
 ['인천', '남동구', '논현동', '620-8'],
 ['인천', '남동구', '논현동', '752-1'],
 ['인천', '남동구', '만수동', '1045', '103호'],
 ['인천', '남동구', '만수동', '1118-2'],
 ['인천', '남동구', '간석3동', '921-14'],
 ['인천', '남동구', '서창동', '706'],
 ['인천', '남동구', '논현동', '671-3'],
 ['인천', '동구', '송림동', '234-1'],
 ['인천', '부평구', '갈산동', '55-8'],
 ['인천', '부평구', '부개동', '12-176'],
 ['인천', '부평구', '부평동', '451-30'],
 ['인천', '부평구', '부평동', '889-8'],
 ['인천', '부평구', '부평동', '192-14'],
 ['인천', '부평구', '산곡동', '369-270'],
 ['인천', '부평구', '산곡동', '119-54'],
 ['인천', '부평구', '산곡2동', '251-1'],
 ['인천', '부평구', '삼산동', '433-1'],
 ['인천', '부평구', '십정동', '440-11'],
 ['인천', '부평구', '청천동', '14-8'],
 ['인천', '서구', '가정동', '614-14'],
 ['인천', '서구', '가좌동', '30-78'],
 ['인천', '서구', '검단로', '왕길동', '637-1'],
 ['인천', '서구', '검암동', '626-2번지', '태건프라자', '105호'],
 ['인천', '서구', '마전동', '585'],
 ['인천', '서구', '당하동', '1033-3', '조이빌', '103'],
 ['인천', '서구', '가정동', '505-4'],
 ['인천', '서구', '심곡동', '257-15'],
 ['인천', '서구', '연희동', '799-8', '우리프라자', '1층'],
 ['인천', '서구', '청라동', '152-15'],
 ['인천', '연수구', '동춘동', '934-1'],
 ['인천', '연수구', '선학동', '406-2'],
 ['인천', '연수구', '송도동', '21-59', '302동', '102호'],
 ['인천', '연수구', '송도동', '3-2'],
 ['인천', '연수구', '송도동', '155(송도아메리칸타운파크)'],
 ['인천', '연수구', '연수동', '626'],
 ['인천', '연수구', '옥련동', '194-4'],
 ['인천', '중구', '운서동', '2801-3'],
 ['인천', '중구', '중산동', '1884-4', '108,109호'],
 ['광주', '동구', '장동', '16-4'],
 ['광주', '서구', '쌍촌동', '881번지'],
 ['광주', '남구', '노대동', '814'],
 ['광주', '서구', '화정동', '178-128'],
 ['광주', '서구', '동천동', '598'],
 ['광주', '북구', '두암2동', '826-50'],
 ['광주', '서구', '금호동', '813', '대주파크빌상가', '124동', '114호,', '115호'],
 ['광주', '북구', '문흥동', '980-15'],
 ['광주', '남구', '서동', '71-15'],
 ['광주', '남구', '주월1동', '1253-4'],
 ['광주', '남구', '봉선2동', '475'],
 ['광주', '서구', '치평동', '1258'],
 ['광주', '광산구', '선암동', '777'],
 ['광주', '광산구', '소촌동', '244-6'],
 ['광주', '광산구', '도산동', '1143'],
 ['광주', '광산구', '장덕동', '1479번지', '1층'],
 ['광주', '광산구', '수완동', '1128번지', '102호'],
 ['광주', '광산구', '신가동', '974-6'],
 ['광주', '광산구', '신창동', '1236-1'],
 ['광주', '서구', '쌍촌동', '147'],
 ['광주', '광산구', '선암동', '777'],
 ['광주', '광산구', '소촌동', '244-6'],
 ['광주', '광산구', '도산동', '1143'],
 ['광주', '광산구', '장덕동', '1479번지', '1층'],
 ['광주', '광산구', '수완동', '1128번지', '102호'],
 ['광주', '광산구', '신가동', '974-6'],
 ['광주', '광산구', '신창동', '1236-1'],
 ['광주', '광산구', '월곡2동', '683-1'],
 ['광주', '광산구', '산월동', '884-2'],
 ['광주', '광산구', '쌍암동', '655-4번지'],

In [5]:
addr2 = []

for i in range(len(addr)):
  if addr[i][0] == "서울": addr[i][0] = "서울특별시"
  elif addr[i][0] == "부산": addr[i][0] = "부산광역시"
  elif addr[i][0] == "인천": addr[i][0] = "인천광역시"
  elif addr[i][0] == "광주": addr[i][0] = "광주광역시"
  elif addr[i][0] == "대전": addr[i][0] = "대전광역시"
  elif addr[i][0] == "울산": addr[i][0] = "울산광역시"
  elif addr[i][0] == "세종": addr[i][0] = "세종특별자치시"
  elif addr[i][0] == "경기": addr[i][0] = "경기도"
  elif addr[i][0] == "충북": addr[i][0] = "충청북도"
  elif addr[i][0] == "충남": addr[i][0] = "충청남도"
  elif addr[i][0] == "전북": addr[i][0] = "전라북도"
  elif addr[i][0] == "전남": addr[i][0] = "전라남도"
  elif addr[i][0] == "경북": addr[i][0] = "경상북도"
  elif addr[i][0] == "경남": addr[i][0] = "경상남도"
  elif addr[i][0] == "제주": addr[i][0] = "제주특별자치도"

  addr2.append(' '.join(addr[i]))

addr2

['서울특별시 송파구 가락동 75-7',
 '서울특별시 금천구 가산동 371-6 가산비지니스센터 2층',
 '서울특별시 강서구 등촌동 75-1',
 '서울특별시 서초구 서초동 1309-6',
 '서울특별시 강서구 화곡동 986-16',
 '서울특별시 강동구 강일동 679-3 리슈빌오피스텔',
 '서울특별시 구로구 개봉동 403-159',
 '서울특별시 강남구 개포동 1229-18',
 '서울특별시 송파구 가락동 180-9',
 '서울특별시 광진구 화양동 9-18',
 '서울특별시 동대문구 회기동 42-16',
 '서울특별시 강동구 고덕동 650-1',
 '서울특별시 구로구 개봉1동 126-4',
 '서울특별시 노원구 공릉동 338-6',
 '서울특별시 노원구 공릉동 461-1',
 '서울특별시 광진구 광장동 530-13',
 '서울특별시 구로구 구로동 74-30',
 '서울특별시 구로구 구로동 826-1',
 '서울특별시 은평구 갈현동 464-14',
 '서울특별시 광진구 구의동 257-70',
 '서울특별시 강남구 개포동 1229-18',
 '서울특별시 강남구 논현동 164-16',
 '서울특별시 강남구 대치동936',
 '서울특별시 강남구 대치동 989-4',
 '서울특별시 강남구 도곡동 416-4',
 '서울특별시 강남구 삼성동 44-18',
 '서울특별시 강남구 자곡동 611',
 '서울특별시 강남구 신사동 640-5 대성빌딩 1층 1호',
 '서울특별시 강남구 역삼동 837-15',
 '서울특별시 강남구 일원동 645',
 '서울특별시 강남구 수서동 747 삼성아파트 상가 104호',
 '서울특별시 강남구 청담동 65 진흥아파트상가',
 '서울특별시 강동구 강일동 679-3 리슈빌오피스텔',
 '서울특별시 강동구 고덕동 650-1',
 '서울특별시 강동구 길동 347-31',
 '서울특별시 강동구 길동 388-3',
 '서울특별시 강동구 둔촌동 454-5',
 '서울특별시 강동구 명일동 328-2',
 '서울특별시 강동구 고덕동 200-3',
 '서울특별시 강동구 성내2동 509-7 1층',
 '서울특별시 강동구 암사동 504-37',
 '서울특별시 강동구 암사동 446-18',
 '서울특별시 강동구 천호동 550번지 강천빌딩',
 '서울특별시 강북구 우이동 72-148',
 '서울특별시 강북구 미아5동 1264-233',
 '서울특별시 강북구 미아동 55-5',
 '서울특별시 강북구 미아동 131-8',
 '서울특별시 강북구 번동 169-1',
 '서울특별시 강북구 수유동 385-2',
 '서울특별시 강북구 번동 461-127',
 '서울특별시 강서구 등촌동 75-1',
 '서울특별시 강서구 화곡동 986-16',
 '서울특별시 강서구 화곡동 343-62 라인씨티 1층',
 '서울특별시 강서구 등촌동 649-14',
 '서울특별시 강서구 강서로 마곡동 784-11 마곡오드카운티1차 111호',
 '서울특별시 강서구 마곡동 774-1',
 '서울특별시 강서구 내발산동 655-6번지 1층 13호',
 '서울특별시 강서구 방화동 571-1',
 '서울특별시 강서구 방화2동 580-27',
 '서울특별시 강서구 염창동 249-5',
 '서울특별시 강서구 화곡동 400-45',
 '서울특별시 관악구 봉천동 861-7',
 '서울특별시 관악구 봉천동 1674-20',
 '서울특별시 관악구 봉천동 1632-9',
 '서울특별시 관악구 봉천동 931-12',
 '서울특별시 관악구 봉천3동 7-291',
 '서울특별시 관악구 신림동 518-56',
 '서울특별시 관악구 신림동 1680-15',
 '서울특별시 관악구 신림동 241-66',
 '서울특별시 광진구 화양동 9-18',
 '서울특별시 광진구 광장동 530-13',
 '서울특별시 광진구 구의동 257-70',
 '서울특별시 광진구 자양3동 584-28',
 '서울특별시 광진구 자양동 624-42',
 '서울특별시 광진구 중곡동 243-1',
 '서울특별시 광진구 중곡동 24-2',
 '서울특별시 구로구 개봉동 403-159',
 '서울특별시 구로구 개봉1동 126-4',
 '서울특별시 구로구 구로동 74-30',
 '서울특별시 구로구 구로동 826-1',
 '서울특별시 구로구 구로동 704-38',
 '서울특별시 구로구 고척동 343',
 '서울특별시 구로구 신도림동 648 신도림6차대림아파트 상가 902동 111호',
 '서울특별시 구로구 오류1동 10-3',
 '서울특별시 구로구 오류동 203-1 1층',
 '서울특별시 금천구 가산동 371-6 가산비지니스센터 2층',
 '서울특별시 금천구 독산동 888-20 102호,103호',
 '서울특별시 금천구 독산동 1059-4',
 '서울특별시 금천구 시흥2동 264-17',
 '서울특별시 금천구 시흥1동 905-5',
 '서울특별시 노원구 공릉동 338-6',
 '서울특별시 노원구 공릉동 461-1',
 '서울특별시 노원구 상계동 749-5',
 '서울특별시 노원구 상계동 456-70',
 '서울특별시 노원구 중계동 137-39 정진빌라 1층',
 '서울특별시 노원구 월계1동 73-13',
 '서울특별시 노원구 상계동 1118',
 '서울특별시 노원구 중계1동 360-9',
 '서울특별시 노원구 중계동 503',
 '서울특별시 노원구 하계1동 251 청구상가 201동 101호',
 '서울특별시 도봉구 도봉2동 623-163',
 '서울특별시 도봉구 방학동 659-32',
 '서울특별시 도봉구 방학동 263-56',
 '서울특별시 도봉구 쌍문3동 88-127',
 '서울특별시 도봉구 창동 568-2',
 '서울특별시 도봉구 창동 296-37',
 '서울특별시 동대문구 회기동 42-16',
 '서울특별시 동대문구 답십리동 53-50',
 '서울특별시 동대문구 전농1동 141-141',
 '서울특별시 동대문구 이문동 255-222',
 '서울특별시 동대문구 제기동 142-8',
 '서울특별시 동대문구 왕산로28길 55',
 '서울특별시 동대문구 전농동 1-171',
 '서울특별시 동대문구 장안동 375-3',
 '서울특별시 동대문구 청량리동 50-3',
 '서울특별시 동작구 노량진동 37-1',
 '서울특별시 동작구 사당3동 155-2 1F',
 '서울특별시 동작구 사당동 220-119',
 '서울특별시 동작구 상도동 535 상도2차 두산위브트레지움아파트 상가',
 '서울특별시 동작구 상도1동 587',
 '서울특별시 동작구 신대방동 607-28',
 '서울특별시 동작구 대방동 407-46',
 '서울특별시 동작구 흑석동 180-6',
 '서울특별시 마포구 도화동 179-8 1,2층',
 '서울특별시 마포구 망원동 482-9',
 '서울특별시 마포구 상암동 34-45',
 '서울특별시 마포구 성산동 592',
 '서울특별시 마포구 신공덕동 159(신공덕 래미안상가 1동109호)',
 '서울특별시 마포구 신수동 451번지 세양청마루아파트 상가 101호',
 '서울특별시 마포구 아현동 774 마포래미안 푸르지오 101동 상가 114호',
 '서울특별시 마포구 연남동 369-20',
 '서울특별시 마포구 서교동 371-3',
 '서울특별시 서대문구 냉천동 226',
 '서울특별시 서대문구 남가좌동 344-7',
 '서울특별시 서대문구 북가좌동 385-8',
 '서울특별시 서대문구 북아현동 1006',
 '서울특별시 서대문구 창천동 41-14',
 '서울특별시 서대문구 연희3동 344-26',
 '서울특별시 서대문구 홍제동 279-52',
 '서울특별시 서대문구 홍제동 326-20',
 '서울특별시 서초구 서초동 1309-6',
 '서울특별시 서초구 반포동 1053 H동 26호',
 '서울특별시 서초구 반포동 53-7',
 '서울특별시 서초구 방배동 761-8',
 '서울특별시 서초구 방배동 912-8',
 '서울특별시 서초구 서초동 1357-56',
 '서울특별시 서초구 서초동 1669-15',
 '서울특별시 서초구 서초동 1579-5',
 '서울특별시 서초구 양재동 327-2',
 '서울특별시 서초구 우면동 720',
 '서울특별시 서초구 잠원동 15-4',
 '서울특별시 성동구 금호동4가 1380',
 '서울특별시 성동구 성수동2가 235-1',
 '서울특별시 성동구 성수동2가 289-251',
 '서울특별시 성동구 하왕십리동 946-15',
 '서울특별시 성동구 홍익동 131-1',
 '서울특별시 성동구 응봉동 100',
 '서울특별시 성동구 행당동 3-29',
 '서울특별시 성북구 하월곡동 17-1',
 '서울특별시 성북구 동소문동 6가 227 1층',
 '서울특별시 성북구 보문동2가 40',
 '서울특별시 성북구 화랑로 265',
 '서울특별시 성북구 정릉4동 285-4',
 '서울특별시 성북구 정릉동 175-24',
 '서울특별시 성북구 종암동 3-544',
 '서울특별시 송파구 가락동 75-7',
 '서울특별시 송파구 가락동 180-9',
 '서울특별시 송파구 거여동 32-6',
 '서울특별시 송파구 문정동 620 송파푸르지오시티 B09호',
 '서울특별시 송파구 방이동 59-1',
 '서울특별시 송파구 오금동 41-23 성암빌딩 1층',
 '서울특별시 송파구 석촌동 163-1',
 '서울특별시 송파구 송파동 147',
 '서울특별시 송파구 풍납동 401-4',
 '서울특별시 송파구 장지동 894 위례아이파크 상가1동 103호, 104호',
 '서울특별시 송파구 잠실본동 313-8',
 '서울특별시 송파구 신천동 11-4',
 '서울특별시 송파구 문정동 102-1',
 '서울특별시 송파구 가락동 479 헬리오시티상가 A동 3,4호',
 '서울특별시 양천구 목동 722-8 호성빌딩',
 '서울특별시 양천구 목동 797-3',
 '서울특별시 양천구 목동 909-8 이화프라자 1층 101호',
 '서울특별시 양천구 목동 940 현대아이파크상가 102',
 '서울특별시 양천구 신월동 602-8',
 '서울특별시 양천구 신월7동 972-6',
 '서울특별시 양천구 신정동 1022-5',
 '서울특별시 양천구 신정동 1267 목동뉴프라자',
 '서울특별시 양천구 신정동 1296 아이파크 상가 1층',
 '서울특별시 양천구 신월동 23-17',
 '서울특별시 영등포구 영등포동8가 35-1',
 '서울특별시 영등포구 대림3동 783-6',
 '서울특별시 영등포구 문래동3가 77-34',
 '서울특별시 영등포구 양평동4가 147-3',
 '서울특별시 영등포구 신길동 296-14',
 '서울특별시 영등포구 신길7동 674',
 '서울특별시 영등포구 신길동 445-2',
 '서울특별시 영등포구 여의도동 44-31',
 '서울특별시 영등포구 신길동 232-42',
 '서울특별시 영등포구 영등포동3가 21-10',
 '서울특별시 용산구 이촌1동 301-153 오성상가 103',
 '서울특별시 용산구 보광동 217-13',
 '서울특별시 용산구 청파동2가 90-11',
 '서울특별시 용산구 한강로2가 122-5',
 '서울특별시 용산구 용문동 28-26',
 '서울특별시 용산구 한남동 828',
 '서울특별시 용산구 후암동 244-59',
 '서울특별시 은평구 갈현동 464-14',
 '서울특별시 은평구 녹번동 82-47',
 '서울특별시 은평구 대조동 231',
 '서울특별시 은평구 불광동 554-1 라비앙프라자1층 101호',
 '서울특별시 은평구 신사동 29-13',
 '서울특별시 은평구 역촌동 55-1',
 '서울특별시 은평구 불광동 484-72',
 '서울특별시 은평구 진관동 22 은평뉴타운상가 914-103호',
 '서울특별시 은평구 응암동 236-33',
 '서울특별시 은평구 응암동 595-51',
 '서울특별시 은평구 증산동 209-18',
 '서울특별시 종로구 명륜동4가 113-1',
 '서울특별시 종로구 숭인2동 183-13',
 '서울특별시 종로구 화동 138-7',
 '서울특별시 종로구 관철동 13-13',
 '서울특별시 종로구 평창동 158-1',
 '서울특별시 중구 창신동 464-6',
 '서울특별시 중구 태평로2가 55',
 '서울특별시 중구 신당동 846',
 '서울특별시 중구 신당동 374-14',
 '서울특별시 중랑구 망우동 149-7',
 '서울특별시 중랑구 면목본동 72-43',
 '서울특별시 중랑구 면목2동 191-126',
 '서울특별시 중랑구 묵동 175-2',
 '서울특별시 중랑구 면목동 496-14',
 '서울특별시 중랑구 상봉동 91-1',
 '서울특별시 중랑구 신내동 797',
 '서울특별시 중랑구 중화동 304-34',
 '부산광역시 부산진구 가야동 478',
 '부산광역시 남구 감만1동 158-6',
 '부산광역시 부산진구 개금동 2-1',
 '부산광역시 부산진구 개금1동 201-6',
 '부산광역시 연제구 거제동 891-14',
 '부산광역시 수영구 광안동 168-3',
 '부산광역시 사상구 괘법동 516-1',
 '부산광역시 사하구 괴정동 487-24',
 '부산광역시 금정구 구서2동 1024-1',
 '부산광역시 북구 구포3동 1228-1',
 '부산광역시 강서구 명지동 3412-6',
 '부산광역시 북구 금곡동 57-6',
 '부산광역시 기장군 기장읍 동부리 134-2',
 '부산광역시 서구 충무동2가 3-1',
 '부산광역시 금정구 남산동 99-6',
 '부산광역시 중구 중앙동1가 23-6',
 '부산광역시 사하구 다대2동 85-5',
 '부산광역시 사하구 다대동 1014',
 '부산광역시 부산진구 당감동 367-2',
 '부산광역시 사하구 괴정동 577-42',
 '부산광역시 강서구 명지동 3412-6',
 '부산광역시 강서구 명지동 3432-1 2동 102호',
 '부산광역시 강서구 명지동 3256-5',
 '부산광역시 강서구 신호동 317-15',
 '부산광역시 강서구 지사동 1191-5',
 '부산광역시 금정구 구서2동 1024-1',
 '부산광역시 금정구 남산동 99-6',
 '부산광역시 금정구 부곡동 23-15',
 '부산광역시 금정구 부곡1동 324-20',
 '부산광역시 금정구 금강로 장전동 418-13',
 '부산광역시 금정구 서동 210-6',
 '부산광역시 금정구 장전동 134-19',
 '부산광역시 기장군 기장읍 동부리 134-2',
 '부산광역시 기장군 일광면 삼성리 833-4',
 '부산광역시 기장군 정관면 매학리 751-8',
 '부산광역시 기장군 모전리 747-7',
 '부산광역시 남구 감만1동 158-6',
 '부산광역시 남구 대연동 1013-8',
 '부산광역시 남구 대연동 52-7',
 '부산광역시 남구 대연동 1161-9',
 '부산광역시 남구 용호동 176-30',
 '부산광역시 남구 대연동 1543-33',
 '부산광역시 남구 문현동 359-5',
 '부산광역시 남구 문현1동 127-56',
 '부산광역시 남구 용호동 555-19',
 '부산광역시 동구 범일동 833-2',
 '부산광역시 동구 수정동 295-3',
 '부산광역시 동구 초량동 132-1',
 '부산광역시 동래구 명륜1동 673-9',
 '부산광역시 동래구 명장동 26-24번지 국제아파트 상가 106호',
 '부산광역시 동래구 복천동 476-1',
 '부산광역시 동래구 사직동 137-5번지',
 '부산광역시 동래구 사직동 89-16',
 '부산광역시 동래구 수안동 192-4',
 '부산광역시 동래구 안락동 670-13',
 '부산광역시 동래구 온천동 210-5번지',
 '부산광역시 동래구 온천동 1411-47',
 '부산광역시 동래구 안락동 471-41',
 '부산광역시 부산진구 가야동 478',
 '부산광역시 부산진구 개금동 2-1',
 '부산광역시 부산진구 개금1동 201-6',
 '부산광역시 부산진구 당감동 367-2',
 '부산광역시 부산진구 범천동 1278-11',
 '부산광역시 부산진구 부암동 301-33',
 '부산광역시 부산진구 부전동 266-24',
 '부산광역시 부산진구 양정동 310-6',
 '부산광역시 부산진구 연지동 40-12',
 '부산광역시 부산진구 초읍동 288-6',
 '부산광역시 북구 구포3동 1228-1',
 '부산광역시 북구 금곡동 57-6',
 '부산광역시 북구 덕천3동 781-2',
 '부산광역시 북구 덕천동 402-12',
 '부산광역시 북구 만덕동 294',
 '부산광역시 북구 만덕3동 915-6',
 '부산광역시 북구 화명동 749',
 '부산광역시 북구 화명동 182-5(2층)',
 '부산광역시 북구 화명동 2266-1',
 '부산광역시 사상구 괘법동 516-1',
 '부산광역시 사상구 덕포동 767-10',
 '부산광역시 사상구 주례동 55-176',
 '부산광역시 사상구 모라동 1349-',
 '부산광역시 사상구 주례2동 3-17',
 '부산광역시 사상구 엄궁동 40-94',
 '부산광역시 사상구 학장동 산149-16',
 '부산광역시 사하구 괴정동 487-24',
 '부산광역시 사하구 다대2동 85-5',
 '부산광역시 사하구 다대동 1014',
 '부산광역시 사하구 괴정동 577-42',
 '부산광역시 사하구 신평동 262-20',
 '부산광역시 사하구 장림동 590',
 '부산광역시 사하구 하단2동 506-15',
 '부산광역시 사하구 하단동 605-42',
 '부산광역시 강서구 명지동 3412-6',
 '부산광역시 서구 충무동2가 3-1',
 '부산광역시 서구 서대신동1가 163-1',
 '부산광역시 강서구 명지동 3432-1 2동 102호',
 '부산광역시 강서구 명지동 3256-5',
 '부산광역시 서구 암남동 64-2 상가동 108호,109호(암남동)',
 '부산광역시 강서구 신호동 317-15',
 '부산광역시 서구 부민동1가 11-3',
 '부산광역시 강서구 지사동 1191-5',
 '부산광역시 수영구 광안동 168-3',
 '부산광역시 수영구 망미동 413-11',
 '부산광역시 수영구 민락동 165-15',
 '부산광역시 수영구 수영동 503-23',
 '부산광역시 연제구 거제동 891-14',
 '부산광역시 연제구 거제3동 34-19',
 '부산광역시 연제구 연산동 479-9',
 '부산광역시 연제구 연산4동 578-1 삼익아파트 상가 101호',
 '부산광역시 연제구 연산동 2133-48',
 '부산광역시 영도구 남항동1가 82',
 '부산광역시 영도구 동삼동 219-146',
 '부산광역시 영도구 영선동1가 69-2, 69-3',
 '부산광역시 영도구 청학동 13-14',
 '부산광역시 중구 중앙동1가 23-6',
 '부산광역시 중구 대청동4가 82-13',
 '부산광역시 해운대구 우동 1434-2',
 '부산광역시 해운대구 반송2동 216-150',
 '부산광역시 해운대구 반여동 1628-5',
 '부산광역시 해운대구 송정동 227-7',
 '부산광역시 해운대구 우동 1090-13',
 '부산광역시 해운대구 반여동 1291-1019',
 '부산광역시 해운대구 재송동 1083-10',
 '부산광역시 해운대구 좌동 970',
 '부산광역시 해운대구 좌동 1341-8',
 '부산광역시 해운대구 좌동 1484-1',
 '부산광역시 해운대구 우동 639-4',
 '대구 달서구 감삼동 317-3',
 '대구시 남구 양지로 107',
 '대구 북구 관음동 1383-9',
 '대구 북구 태전동 1074-6',
 '대구 달성군 구지면 응암리 1204-2',
 '대구 북구 사수동 912',
 '대구 중구 남산3동 2466-14',
 '대구 서구 내당동 219-7',
 '대구 달성군 논공읍 북리 803-128',
 '대구 달성군 다사읍 죽곡리 809-1',
 '대구 서구 비산동 440-5',
 '대구 달서구 도원동 1442-2 1층 107호',
 '대구 동구 각산동 1098-5 102호',
 '대구 남구 대명동 1098-4',
 '대구 동구 신암동 345-3',
 '대구 북구 동변동 669-4',
 '대구 북구 동천동 906-3',
 '대구 동구 검사동 1111',
 '대구 동구 동호동 384-7',
 '대구 달서구 두류동 620-12',
 '대구시 남구 양지로 107',
 '대구 남구 대명동 1098-4',
 '대구 남구 봉덕동 687-32',
 '대구 남구 대명동 780-3',
 '대구 남구 이천동 184-9',
 '대구 달서구 감삼동 317-3',
 '대구 달서구 도원동 1442-2 1층 107호',
 '대구 달서구 두류동 620-12',
 '대구 달서구 상인동 1555-1',
 '대구 달서구 신당동 1761-5',
 '대구 달서구 송현1동 207-2',
 '대구 달서구 월성동 1264번지 트럼프스타 B/D 106호',
 '대구 달서구 용산1동 954-6',
 '대구 달서구 용산동 499-2',
 '대구 달서구 본동 1135-4',
 '대구 달서구 장기동 826-6',
 '대구 달서구 진천동 504',
 '대구 달서구 호산동 357-116',
 '대구 달성군 구지면 응암리 1204-2',
 '대구 달성군 논공읍 북리 803-128',
 '대구 달성군 다사읍 죽곡리 809-1',
 '대구 달성군 화원읍 명곡리 320-1',
 '대구 달성군 다사읍 서재리 423-15',
 '대구 달성군 옥포읍 교항리 2911',
 '대구 달성군 유가면 봉리 606 하이젠스타 115호',
 '대구 달성군 화원읍 천내리 241-1',
 '대구 동구 각산동 1098-5 102호',
 '대구 동구 신암동 345-3',
 '대구 동구 검사동 1111',
 '대구 동구 동호동 384-7',
 '대구 동구 방촌동 1118-121',
 '대구 동구 신천동 501-5',
 '대구 동구 신청동 377-12',
 '대구 동구 율하동 1311번지 102호',
 '대구 동구 지묘동 808-3',
 '대구 동구 지저동 833-15',
 '대구 북구 관음동 1383-9',
 '대구 북구 태전동 1074-6',
 '대구 북구 사수동 912',
 '대구 북구 동변동 669-4',
 '대구 북구 동천동 906-3',
 '대구 북구 복현동 426-5',
 '대구 북구 복현동 539 -110 복현서한타운 상가 103호',
 '대구 북구 산격동 1400-20',
 '대구 북구 대현동 153-4',
 '대구 북구 연경동 949-1',
 '대구 북구 노원동3가 892-1',
 '대구 북구 읍내동 1449 202동 103호',
 '대구 북구 칠성동2가 42-9',
 '대구 북구 침산동 457-31',
 '대구 북구 태전동 254-30',
 '대구 북구 매천동 682',
 '대구 북구 학정동 282-14',
 '대구 달서구 감삼동 317-3',
 '대구 서구 내당동 219-7',
 '대구 서구 비산동 440-5',
 '대구 달서구 도원동 1442-2 1층 107호',
 '대구 달서구 두류동 620-12',
 '대구 달서구 상인동 1555-1',
 '대구 달서구 신당동 1761-5',
 '대구 달서구 송현1동 207-2',
 '대구 달서구 월성동 1264번지 트럼프스타 B/D 106호',
 '대구 달서구 용산1동 954-6',
 '대구 달서구 용산동 499-2',
 '대구 달서구 본동 1135-4',
 '대구 달서구 장기동 826-6',
 '대구 달서구 진천동 504',
 '대구 서구 평리동 1217-2',
 '대구 달서구 호산동 357-116',
 '대구 수성구 만촌동 849-2',
 '대구 수성구 만촌1동 1330-12',
 '대구 수성구 범물동 1374-4',
 '대구 수성구 범어동 203-18',
 '대구 수성구 범어동 478-12',
 '대구 수성구 수성동4가 1022-11',
 '대구 수성구 두산동 653-5',
 '대구 수성구 매호동 1328-12',
 '대구 수성구 시지동 489-2',
 '대구 수성구 신매동 593-4',
 '대구 수성구 중동 97-5',
 '대구 수성구 상동 380-2',
 '대구 수성구 두산동 133-1',
 '대구 중구 남산3동 2466-14',
 '대구 중구 남일동 33-9',
 '인천광역시 서구 가정동 614-14',
 '인천광역시 서구 가좌동 30-78',
 '인천광역시 남동구 구월동 70-80',
 '인천광역시 부평구 갈산동 55-8',
 '인천광역시 강화군 강화읍 갑곳리 199-1',
 '인천광역시 서구 검단로 왕길동 637-1',
 '인천광역시 서구 검암동 626-2번지 태건프라자 105호',
 '인천광역시 계양구 계산동 1081-10',
 '인천광역시 계양구 계산동 61-2',
 '인천광역시 계양구 계산동 942-30',
 '인천광역시 중구 운서동 2801-3',
 '인천광역시 남구 관교동 321-5',
 '인천광역시 남동구 구월동 1133-13',
 '인천광역시 남동구 구월동 1517-2',
 '인천광역시 남동구 논현동 620-8',
 '인천광역시 남동구 논현동 752-1',
 '인천광역시 서구 마전동 585',
 '인천광역시 미추홀구 도화동 1005-3 스카이프라자2',
 '인천광역시 연수구 동춘동 934-1',
 '인천광역시 남동구 만수동 1045 103호',
 '인천광역시 강화군 강화읍 갑곳리 199-1',
 '인천광역시 계양구 계산동 1081-10',
 '인천광역시 계양구 계산동 61-2',
 '인천광역시 계양구 계산동 942-30',
 '인천광역시 계양구 박촌동 52-3',
 '인천광역시 계양구 작전동 149-1',
 '인천광역시 계양구 효성1동 21-11 현대아파트 상가동 101호, 102호, 103호',
 '인천광역시 계양구 효성2동 273-3',
 '인천광역시 남구 관교동 321-5',
 '인천광역시 남구 용현동 558-32',
 '인천광역시 남구 용현동 630-45',
 '인천광역시 남구 주안동 1523-2',
 '인천광역시 남구 학익동 293-37',
 '인천광역시 남동구 구월동 70-80',
 '인천광역시 남동구 구월동 1133-13',
 '인천광역시 남동구 구월동 1517-2',
 '인천광역시 남동구 논현동 620-8',
 '인천광역시 남동구 논현동 752-1',
 '인천광역시 남동구 만수동 1045 103호',
 '인천광역시 남동구 만수동 1118-2',
 '인천광역시 남동구 간석3동 921-14',
 '인천광역시 남동구 서창동 706',
 '인천광역시 남동구 논현동 671-3',
 '인천광역시 남동구 구월동 70-80',
 '인천광역시 남동구 구월동 1133-13',
 '인천광역시 남동구 구월동 1517-2',
 '인천광역시 남동구 논현동 620-8',
 '인천광역시 남동구 논현동 752-1',
 '인천광역시 남동구 만수동 1045 103호',
 '인천광역시 남동구 만수동 1118-2',
 '인천광역시 남동구 간석3동 921-14',
 '인천광역시 남동구 서창동 706',
 '인천광역시 남동구 논현동 671-3',
 '인천광역시 동구 송림동 234-1',
 '인천광역시 부평구 갈산동 55-8',
 '인천광역시 부평구 부개동 12-176',
 '인천광역시 부평구 부평동 451-30',
 '인천광역시 부평구 부평동 889-8',
 '인천광역시 부평구 부평동 192-14',
 '인천광역시 부평구 산곡동 369-270',
 '인천광역시 부평구 산곡동 119-54',
 '인천광역시 부평구 산곡2동 251-1',
 '인천광역시 부평구 삼산동 433-1',
 '인천광역시 부평구 십정동 440-11',
 '인천광역시 부평구 청천동 14-8',
 '인천광역시 서구 가정동 614-14',
 '인천광역시 서구 가좌동 30-78',
 '인천광역시 서구 검단로 왕길동 637-1',
 '인천광역시 서구 검암동 626-2번지 태건프라자 105호',
 '인천광역시 서구 마전동 585',
 '인천광역시 서구 당하동 1033-3 조이빌 103',
 '인천광역시 서구 가정동 505-4',
 '인천광역시 서구 심곡동 257-15',
 '인천광역시 서구 연희동 799-8 우리프라자 1층',
 '인천광역시 서구 청라동 152-15',
 '인천광역시 연수구 동춘동 934-1',
 '인천광역시 연수구 선학동 406-2',
 '인천광역시 연수구 송도동 21-59 302동 102호',
 '인천광역시 연수구 송도동 3-2',
 '인천광역시 연수구 송도동 155(송도아메리칸타운파크)',
 '인천광역시 연수구 연수동 626',
 '인천광역시 연수구 옥련동 194-4',
 '인천광역시 중구 운서동 2801-3',
 '인천광역시 중구 중산동 1884-4 108,109호',
 '광주광역시 동구 장동 16-4',
 '광주광역시 서구 쌍촌동 881번지',
 '광주광역시 남구 노대동 814',
 '광주광역시 서구 화정동 178-128',
 '광주광역시 서구 동천동 598',
 '광주광역시 북구 두암2동 826-50',
 '광주광역시 서구 금호동 813 대주파크빌상가 124동 114호, 115호',
 '광주광역시 북구 문흥동 980-15',
 '광주광역시 남구 서동 71-15',
 '광주광역시 남구 주월1동 1253-4',
 '광주광역시 남구 봉선2동 475',
 '광주광역시 서구 치평동 1258',
 '광주광역시 광산구 선암동 777',
 '광주광역시 광산구 소촌동 244-6',
 '광주광역시 광산구 도산동 1143',
 '광주광역시 광산구 장덕동 1479번지 1층',
 '광주광역시 광산구 수완동 1128번지 102호',
 '광주광역시 광산구 신가동 974-6',
 '광주광역시 광산구 신창동 1236-1',
 '광주광역시 서구 쌍촌동 147',
 '광주광역시 광산구 선암동 777',
 '광주광역시 광산구 소촌동 244-6',
 '광주광역시 광산구 도산동 1143',
 '광주광역시 광산구 장덕동 1479번지 1층',
 '광주광역시 광산구 수완동 1128번지 102호',
 '광주광역시 광산구 신가동 974-6',
 '광주광역시 광산구 신창동 1236-1',
 '광주광역시 광산구 월곡2동 683-1',
 '광주광역시 광산구 산월동 884-2',
 '광주광역시 광산구 쌍암동 655-4번지',
 '광주광역시 광산구 쌍암동 694-60',
 '광주광역시 광산구 산정동 977-13',
 '광주광역시 광산구 산정동 1039',
 '광주광역시 남구 노대동 814',
 '광주광역시 남구 서동 71-15',
 '광주광역시 남구 주월1동 1253-4',
 '광주광역시 남구 봉선2동 475',
 '광주광역시 남구 월산동 1034-17',
 '광주광역시 남구 진월동 870번지 한국아델리움 2차상가 230동 102호',
 '광주광역시 동구 장동 16-4',
 '광주광역시 동구 지산동 500번지',
 '광주광역시 동구 학동 735-16',
 '광주광역시 북구 두암2동 826-50',
 '광주광역시 북구 문흥동 980-15',
 '광주광역시 북구 양산동 877-1 1층',
 '광주광역시 북구 연제동 41-3',
 '광주광역시 북구 오치동 785-4',
 '광주광역시 북구 운암3동 1051-5',
 '광주광역시 북구 운암동 운암동 130-1',
 '광주광역시 북구 일곡동 834-11',
 '광주광역시 북구 용봉동 157-20',
 '광주광역시 북구 신용동 693',
 '광주광역시 서구 쌍촌동 881번지',
 '광주광역시 서구 화정동 178-128',
 '광주광역시 서구 동천동 598',
 '광주광역시 서구 금호동 813 대주파크빌상가 124동 114호, 115호',
 '광주광역시 서구 치평동 1258',
 '광주광역시 서구 쌍촌동 147',
 '광주광역시 서구 풍암동 1111-2',
 '광주광역시 서구 화정동 824-16',
 '광주광역시 서구 농성동 666-1 1층 113,114호',
 '대전광역시 동구 가오동 235-12',
 '대전광역시 서구 가장동 50-45',
 '대전광역시 서구 갈마동 394-29',
 '대전광역시 유성구 원내동 829 외 1필지',
 '대전광역시 서구 관저동 1354',
 '대전광역시 유성구 관평동 1056',
 '대전광역시 유성구 노은동 553-9 스타돔 120호',
 '대전광역시 유성구 지족동 985-2',
 '대전광역시 중구 대사동 69-53',
 '대전광역시 중구 대흥동 204-3',
 '대전광역시 서구 도마동 114-19',
 '대전광역시 유성구 상대동 469-9',
 '대전광역시 서구 가수원동 1036',
 '대전광역시 서구 둔산2동 1093',
 '대전광역시 서구 둔산동 1851',
 '대전광역시 서구 만년동 316',
 '대전광역시 중구 문화동 466-16',
 '대전광역시 대덕구 중리동 385-26',
 '대전광역시 서구 복수동 622',
 '대전광역시 동구 가양동 88-1 조일아파트상가 A동',
 '대전광역시 대덕구 중리동 385-26',
 '대전광역시 대덕구 송촌동 454-4',
 '대전광역시 대덕구 석봉동 309-1',
 '대전광역시 대덕구 한남로 오정동 223-260',
 '대전광역시 동구 가오동 235-12',
 '대전광역시 동구 가양동 88-1 조일아파트상가 A동',
 '대전광역시 동구 용운동 306-3',
 '대전광역시 동구 대동 192-1',
 '대전광역시 서구 가장동 50-45',
 '대전광역시 서구 갈마동 394-29',
 '대전광역시 서구 관저동 1354',
 '대전광역시 서구 도마동 114-19',
 '대전광역시 서구 가수원동 1036',
 '대전광역시 서구 둔산2동 1093',
 '대전광역시 서구 둔산동 1851',
 '대전광역시 서구 만년동 316',
 '대전광역시 서구 복수동 622',
 '대전광역시 서구 월평동 525',
 '대전광역시 서구 탄방동 723',
 '대전광역시 유성구 원내동 829 외 1필지',
 '대전광역시 유성구 관평동 1056',
 '대전광역시 유성구 노은동 553-9 스타돔 120호',
 '대전광역시 유성구 지족동 985-2',
 '대전광역시 유성구 상대동 469-9',
 '대전광역시 유성구 봉산동 198-13',
 '대전광역시 유성구 신성동 137-15',
 '대전광역시 유성구 봉명동 621-1',
 '대전광역시 유성구 문지동 635-8',
 '대전광역시 유성구 덕명동 592-6',
 '대전광역시 중구 대사동 69-53',
 '대전광역시 중구 대흥동 204-3',
 '대전광역시 중구 문화동 466-16',
 '대전광역시 중구 오류동 153-27',
 '대전광역시 중구 중촌동 12-5',
 '대전광역시 중구 유천동 326-13',
 '울산광역시 북구 산하동 89',
 '울산광역시 남구 신정동 1218-7',
 '울산광역시 울주군 삼남면 교동리 1578-1',
 '울산광역시 울주군 범서읍 구영리 801-6',
 '울산광역시 동구 서부동 113-33',
 '울산광역시 울주군 온양읍 대안리 179-10',
 '울산광역시 중구 다운동 536-1',
 '울산광역시 남구 달동 135-2',
 '울산광역시 울주군 덕신리 1294-2',
 '울산광역시 남구 무거동 1484-2',
 '울산광역시 중구 반구동 874-3',
 '울산광역시 중구 반구동 99-17',
 '울산광역시 동구 방어동 1087-9',
 '울산광역시 중구 복산동 399-12',
 '울산광역시 남구 달동 1266-9',
 '울산광역시 남구 삼산동 203-15',
 '울산광역시 중구 성안동 804-10',
 '울산광역시 북구 송정동 407',
 '울산광역시 남구 야음동 692-6',
 '울산광역시 남구 신정3동 177-1',
 '울산광역시 남구 신정동 1218-7',
 '울산광역시 남구 달동 135-2',
 '울산광역시 남구 무거동 1484-2',
 '울산광역시 남구 달동 1266-9',
 '울산광역시 남구 삼산동 203-15',
 '울산광역시 남구 야음동 692-6',
 '울산광역시 남구 신정3동 177-1',
 '울산광역시 남구 선암동 679-3',
 '울산광역시 남구 야음1동 455-8',
 '울산광역시 남구 옥동 1406-17',
 '울산광역시 남구 무거동 583-17',
 '울산광역시 동구 서부동 113-33',
 '울산광역시 동구 방어동 1087-9',
 '울산광역시 동구 전하2동 634-4',
 '울산광역시 동구 일산동 581-36',
 '울산광역시 북구 산하동 89',
 '울산광역시 북구 송정동 407',
 '울산광역시 북구 양정동 497-11',
 '울산광역시 북구 명촌동 692-3',
 '울산광역시 북구 호계동 286-15',
 '울산광역시 북구 신천동 107-4',
 '울산광역시 북구 연암동 414-3',
 '울산광역시 울주군 삼남면 교동리 1578-1',
 '울산광역시 울주군 범서읍 구영리 801-6',
 '울산광역시 울주군 온양읍 대안리 179-10',
 '울산광역시 울주군 덕신리 1294-2',
 '울산광역시 울주군 언양읍 남부리 256-2',
 '울산광역시 울주군 청량면 삼정리 755-1 가동 216호',
 '울산광역시 울주군 범서읍 천상리 650-5',
 '울산광역시 중구 다운동 536-1',
 '울산광역시 중구 반구동 874-3',
 '울산광역시 중구 반구동 99-17',
 '울산광역시 중구 복산동 399-12',
 '울산광역시 중구 성안동 804-10',
 '울산광역시 중구 약사동 629-17',
 '울산광역시 중구 학산동 3-27',
 '울산광역시 중구 우정동 436-41',
 '울산광역시 중구 유곡동 473-8',
 '울산광역시 중구 태화동 117-2',
 '세종특별자치시 고운동 1718',
 '세종특별자치시 다정동 363-10',
 '세종특별자치시 도담동 245-1',
 '세종시 보람동 628-4',
 '세종특별자치시 아름동 1363',
 '세종특별자치시 조치원읍 죽림리 21-1 삼일아파트 상가 109호',
 '세종특별자치시 한솔동 927',
 '세종특별자치시 한솔동 927',
 '세종특별자치시 도담동 245-1',
 '세종특별자치시 아름동 1363',
 '세종시 보람동 628-4',
 '세종특별자치시 고운동 1718',
 '세종특별자치시 조치원읍 죽림리 21-1 삼일아파트 상가 109호',
 '세종특별자치시 다정동 363-10',
 '경기도 파주시 와동동 1557-1',
 '경기도 가평군 가평읍 대곡리 168-5',
 '경기도 구리시 갈매동 608-1 101호, 102호',
 '경기도 용인시 기흥구 구갈동 594 강남피아 118~120호',
 '경기도 고양시 일산동구 정발산동 687-5',
 '경기도 시흥시 거모동 1757-1',
 '경기도 부천시 오정구 고강1동 305-4',
 '경기도 평택시 고덕면 여염리 4434-2',
 '경기도 수원시 권선구 고색동 31-4',
 '경기도 고양시 덕양구 고양동 176-8 104호',
 '경기도 양주시 광사동 657',
 '경기도 안산시 단원구 고잔동 756-1',
 '경기도 안산시 단원구 와동 720-13',
 '경기도 김포시 고촌면 신곡리 1052',
 '경기도 수원시 권선구 곡반정동 584-4',
 '경기도 광주시 곤지암읍 곤지암리 443-9',
 '경기도 안성시 공도읍 만정리 417-98',
 '경기도 과천시 원문동 4 레미안 슈르 A상가(4번지)동 제1층 1023호',
 '경기도 안양시 동안구 관양동 1437-20 1층',
 '경기도 수원시 영통구 이의동 1332 CB 4~5호',
 '경기도 가평군 가평읍 대곡리 168-5',
 '경기도 가평군 청평면 청평리 452-5',
 '경기도 가평군 하면 현리 259-7',
 '경기도 고양시 덕양구 고양동 176-8 104호',
 '경기도 고양시 덕양구 신원동 626-1 1층 상가 5~6호',
 '경기도 고양시 덕양구 성사동 519-2',
 '경기도 고양시 덕양구 도내동 966',
 '경기도 고양시 덕양구 행신동 995-2',
 '경기도 고양시 덕양구 행신동 708-3',
 '경기도 고양시 덕양구 화정동 906-5 1층 102호',
 '경기도 고양시 덕양구 화정동 979-2',
 '경기도 고양시 일산동구 정발산동 687-5',
 '경기도 고양시 일산동구 정발산동 1093',
 '경기도 고양시 일산동구 마두동 753-3',
 '경기도 고양시 일산동구 백석동 1225 중앙프라자 103호',
 '경기도 고양시 일산동구 식사동 1531',
 '경기도 고양시 일산동구 중산동 1667-3',
 '경기도 고양시 일산동구 풍동 1273-5',
 '경기도 고양시 일산동구 백석동 1414-15',
 '경기도 고양시 일산서구 일산동 967-6',
 '경기도 고양시 일산서구 대화동 2126-2 (동남빌딩 101호)',
 '경기도 고양시 일산서구 주엽2동 138 애비뉴상가 1층 1068호',
 '경기도 고양시 일산서구 대화동 2606',
 '경기도 고양시 일산서구 탄현동 1562-5',
 '경기도 과천시 원문동 4 레미안 슈르 A상가(4번지)동 제1층 1023호',
 '경기도 광명시 광명동 295-4',
 '경기도 광명시 일직동 511-5번지 대호M스퀘어 102호, 103호',
 '경기도 광명시 소하동 1240-3',
 '경기도 광명시 소하동 1342-1',
 '경기도 광명시 철산동 210-1',
 '경기도 광명시 철산동 92-1',
 '경기도 광명시 철산동 429',
 '경기도 광명시 하안동 35-5, 영보빌딩 102호',
 '경기도 광주시 곤지암읍 곤지암리 443-9',
 '경기도 광주시 경안동 154-1',

In [6]:
addr2 = pd.DataFrame(addr2, columns = ['address2'])

In [7]:
CB2 = pd.concat([CB, addr2], axis = 1)
CB2.head()

,store,sido,gungu,store_address,address2
0,가락2호,서울,송파구,서울 송파구 가락동 75-7,서울특별시 송파구 가락동 75-7
1,가산디지털,서울,금천구,서울 금천구 가산동 371-6 가산비지니스센터 2층,서울특별시 금천구 가산동 371-6 가산비지니스센터 2층
2,가양,서울,강서구,서울 강서구 등촌동 75-1,서울특별시 강서구 등촌동 75-1
3,강남역,서울,서초구,서울 서초구 서초동 1309-6,서울특별시 서초구 서초동 1309-6
4,강서구청,서울,강서구,서울 강서구 화곡동 986-16,서울특별시 강서구 화곡동 986-16

In [8]:
CB2.to_csv('kyochon_2.csv', encoding = 'CP949', index = False)

In [9]:
import folium

In [10]:
map_osm = folium.Map(location = [35.147002, 129.074268], zoom_start = 16)

In [11]:
map_osm.save('map.html')

In [12]:
CB_geoData = pd.read_csv('kyochon_3.csv', encoding = 'utf-8', engine='python')

In [13]:
map_CB = folium.Map(location = [35.147002, 129.074268], zoom_start = 16)

In [15]:
for i, store in CB_geoData.iterrows():
  folium.Marker(location=[store['_Y'], store['_X']], popup=store['field1'], icon=folium.Icon(color = 'red', icon = 'star')).add_to(map_CB)

In [ ]:
map_CB.save('kyochon_map_CB.html')

In [ ]:
import webbrowser
webbros